name: github pages

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  # cancel-in-progress: false

jobs:
  deploy:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node: [18]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm i
      - run: pnpm run build:theme
      - run: pnpm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          force_orphan: true
