name: github pages

on:
  push:
    branches:
      - main

concurrency:
  group: pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          # latest version will trigger OOM error in github actions
          node-version: 22
          cache: "pnpm"

      - run: pnpm i
      - run: pnpm run build:theme
      - run: pnpm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          force_orphan: true
